#ifndef _GFX9_BLOCKTABLE_H_
#define _GFX9_BLOCKTABLE_H_

namespace gfxip {
namespace gfx9 {
/*
 * The following tables contain register addresses of the SQ counter registers
 */

/*
 * SQ
 */
static const CounterRegInfo SqCounterRegAddr[] = {
    {mmSQ_PERFCOUNTER0_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER0_LO, mmSQ_PERFCOUNTER0_HI},
    {mmSQ_PERFCOUNTER1_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER1_LO, mmSQ_PERFCOUNTER1_HI},
    {mmSQ_PERFCOUNTER2_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER2_LO, mmSQ_PERFCOUNTER2_HI},
    {mmSQ_PERFCOUNTER3_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER3_LO, mmSQ_PERFCOUNTER3_HI},
    {mmSQ_PERFCOUNTER4_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER4_LO, mmSQ_PERFCOUNTER4_HI},
    {mmSQ_PERFCOUNTER5_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER5_LO, mmSQ_PERFCOUNTER5_HI},
    {mmSQ_PERFCOUNTER6_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER6_LO, mmSQ_PERFCOUNTER6_HI},
    {mmSQ_PERFCOUNTER7_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER7_LO, mmSQ_PERFCOUNTER7_HI},
    {mmSQ_PERFCOUNTER8_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER8_LO, mmSQ_PERFCOUNTER8_HI},
    {mmSQ_PERFCOUNTER9_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER9_LO, mmSQ_PERFCOUNTER9_HI},
    {mmSQ_PERFCOUNTER10_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER10_LO, mmSQ_PERFCOUNTER10_HI},
    {mmSQ_PERFCOUNTER11_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER11_LO, mmSQ_PERFCOUNTER11_HI},
    {mmSQ_PERFCOUNTER12_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER12_LO, mmSQ_PERFCOUNTER12_HI},
    {mmSQ_PERFCOUNTER13_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER13_LO, mmSQ_PERFCOUNTER13_HI},
    {mmSQ_PERFCOUNTER14_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER14_LO, mmSQ_PERFCOUNTER14_HI},
    {mmSQ_PERFCOUNTER15_SELECT, mmSQ_PERFCOUNTER_CTRL, mmSQ_PERFCOUNTER15_LO, mmSQ_PERFCOUNTER15_HI}};

static const BlockDelayInfo SqBlockDelayInfo[] = {
  {mmRLC_SPM_SQG_PERFMON_SAMPLE_DELAY, 0x0000002c},
  {mmRLC_SPM_SQG_PERFMON_SAMPLE_DELAY, 0x00000029},
  {mmRLC_SPM_SQG_PERFMON_SAMPLE_DELAY, 0x0000002a},
  {mmRLC_SPM_SQG_PERFMON_SAMPLE_DELAY, 0x00000027},
};

/*
 * IH
 */
static const CounterRegInfo IhCounterRegAddr[] = {
    {mmIH_PERFMON_CNTL, 0, mmIH_PERFCOUNTER0_RESULT, 0},
    {mmIH_PERFMON_CNTL, 0, mmIH_PERFCOUNTER1_RESULT, 0}};

/*
 * GRBM
 */
static const CounterRegInfo GrbmCounterRegAddr[] = {
    {mmGRBM_PERFCOUNTER0_SELECT, 0, mmGRBM_PERFCOUNTER0_LO, mmGRBM_PERFCOUNTER0_HI},
    {mmGRBM_PERFCOUNTER1_SELECT, 0, mmGRBM_PERFCOUNTER1_LO, mmGRBM_PERFCOUNTER1_HI}};

/*
 * GRBM_SE
 */
static const CounterRegInfo GrbmSeCounterRegAddr[] = {
    {mmGRBM_SE0_PERFCOUNTER_SELECT, 0, mmGRBM_SE0_PERFCOUNTER_LO, mmGRBM_SE0_PERFCOUNTER_HI},
    {mmGRBM_SE1_PERFCOUNTER_SELECT, 0, mmGRBM_SE1_PERFCOUNTER_LO, mmGRBM_SE1_PERFCOUNTER_HI},
    {mmGRBM_SE2_PERFCOUNTER_SELECT, 0, mmGRBM_SE2_PERFCOUNTER_LO, mmGRBM_SE2_PERFCOUNTER_HI},
    {mmGRBM_SE3_PERFCOUNTER_SELECT, 0, mmGRBM_SE3_PERFCOUNTER_LO, mmGRBM_SE3_PERFCOUNTER_HI}};

/*
 * PA_SU
 */
static const CounterRegInfo PaSuCounterRegAddr[] = {
    {mmPA_SU_PERFCOUNTER0_SELECT, 0, mmPA_SU_PERFCOUNTER0_LO, mmPA_SU_PERFCOUNTER0_HI},
    {mmPA_SU_PERFCOUNTER1_SELECT, 0, mmPA_SU_PERFCOUNTER1_LO, mmPA_SU_PERFCOUNTER1_HI},
    {mmPA_SU_PERFCOUNTER2_SELECT, 0, mmPA_SU_PERFCOUNTER2_LO, mmPA_SU_PERFCOUNTER2_HI},
    {mmPA_SU_PERFCOUNTER3_SELECT, 0, mmPA_SU_PERFCOUNTER3_LO, mmPA_SU_PERFCOUNTER3_HI}};

static const BlockDelayInfo PaSuBlockDelayInfo[] = {
    { mmRLC_SPM_PA_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_PA_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_PA_PERFMON_SAMPLE_DELAY, 0x00000020},
    { mmRLC_SPM_PA_PERFMON_SAMPLE_DELAY, 0x00000020}};

/*
 * PA_SC
 */
static const CounterRegInfo PaScCounterRegAddr[] = {
    {mmPA_SC_PERFCOUNTER0_SELECT, 0, mmPA_SC_PERFCOUNTER0_LO, mmPA_SC_PERFCOUNTER0_HI},
    {mmPA_SC_PERFCOUNTER1_SELECT, 0, mmPA_SC_PERFCOUNTER1_LO, mmPA_SC_PERFCOUNTER1_HI},
    {mmPA_SC_PERFCOUNTER2_SELECT, 0, mmPA_SC_PERFCOUNTER2_LO, mmPA_SC_PERFCOUNTER2_HI},
    {mmPA_SC_PERFCOUNTER3_SELECT, 0, mmPA_SC_PERFCOUNTER3_LO, mmPA_SC_PERFCOUNTER3_HI},
    {mmPA_SC_PERFCOUNTER4_SELECT, 0, mmPA_SC_PERFCOUNTER4_LO, mmPA_SC_PERFCOUNTER4_HI},
    {mmPA_SC_PERFCOUNTER5_SELECT, 0, mmPA_SC_PERFCOUNTER5_LO, mmPA_SC_PERFCOUNTER5_HI},
    {mmPA_SC_PERFCOUNTER6_SELECT, 0, mmPA_SC_PERFCOUNTER6_LO, mmPA_SC_PERFCOUNTER6_HI},
    {mmPA_SC_PERFCOUNTER7_SELECT, 0, mmPA_SC_PERFCOUNTER7_LO, mmPA_SC_PERFCOUNTER7_HI}};

static const BlockDelayInfo PaScBlockDelayInfo[] = {
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000026},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000026},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000023},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000023},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000021},
    { mmRLC_SPM_SC_PERFMON_SAMPLE_DELAY, 0x00000021}};

/*
 * SPI
 */
static const CounterRegInfo SpiCounterRegAddr[] = {
    {mmSPI_PERFCOUNTER0_SELECT, 0, mmSPI_PERFCOUNTER0_LO, mmSPI_PERFCOUNTER0_HI},
    {mmSPI_PERFCOUNTER1_SELECT, 0, mmSPI_PERFCOUNTER1_LO, mmSPI_PERFCOUNTER1_HI},
    {mmSPI_PERFCOUNTER2_SELECT, 0, mmSPI_PERFCOUNTER2_LO, mmSPI_PERFCOUNTER2_HI},
    {mmSPI_PERFCOUNTER3_SELECT, 0, mmSPI_PERFCOUNTER3_LO, mmSPI_PERFCOUNTER3_HI},
    {mmSPI_PERFCOUNTER4_SELECT, 0, mmSPI_PERFCOUNTER4_LO, mmSPI_PERFCOUNTER4_HI},
    {mmSPI_PERFCOUNTER5_SELECT, 0, mmSPI_PERFCOUNTER5_LO, mmSPI_PERFCOUNTER5_HI}};

static const BlockDelayInfo SpiBlockDelayInfo[] = {
    { mmRLC_SPM_SPI_PERFMON_SAMPLE_DELAY, 0x0000002a},
    { mmRLC_SPM_SPI_PERFMON_SAMPLE_DELAY, 0x0000002a},
    { mmRLC_SPM_SPI_PERFMON_SAMPLE_DELAY, 0x00000027},
    { mmRLC_SPM_SPI_PERFMON_SAMPLE_DELAY, 0x00000027}};

/*
 * TCA
 */
static const CounterRegInfo TcaCounterRegAddr[] = {
    {mmTCA_PERFCOUNTER0_SELECT, 0, mmTCA_PERFCOUNTER0_LO, mmTCA_PERFCOUNTER0_HI},
    {mmTCA_PERFCOUNTER1_SELECT, 0, mmTCA_PERFCOUNTER1_LO, mmTCA_PERFCOUNTER1_HI},
    {mmTCA_PERFCOUNTER2_SELECT, 0, mmTCA_PERFCOUNTER2_LO, mmTCA_PERFCOUNTER2_HI},
    {mmTCA_PERFCOUNTER3_SELECT, 0, mmTCA_PERFCOUNTER3_LO, mmTCA_PERFCOUNTER3_HI}};

static const BlockDelayInfo TcaBlockDelayInfo[] = {
    { mmRLC_SPM_TCA_PERFMON_SAMPLE_DELAY, 0x00000018},
    { mmRLC_SPM_TCA_PERFMON_SAMPLE_DELAY, 0x0000001c}};

/*
 * TCC
 */
static const CounterRegInfo TccCounterRegAddr[] = {
    {mmTCC_PERFCOUNTER0_SELECT, 0, mmTCC_PERFCOUNTER0_LO, mmTCC_PERFCOUNTER0_HI},
    {mmTCC_PERFCOUNTER1_SELECT, 0, mmTCC_PERFCOUNTER1_LO, mmTCC_PERFCOUNTER1_HI},
    {mmTCC_PERFCOUNTER2_SELECT, 0, mmTCC_PERFCOUNTER2_LO, mmTCC_PERFCOUNTER2_HI},
    {mmTCC_PERFCOUNTER3_SELECT, 0, mmTCC_PERFCOUNTER3_LO, mmTCC_PERFCOUNTER3_HI}};

static const BlockDelayInfo TccBlockDelayInfo[] = {
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x0000000F},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000015},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000017},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x0000001d},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x0000001b},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000017},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000013},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x0000000f},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000014},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000018},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x0000001c},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000020},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x0000001d},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000019},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000015},
    { mmRLC_SPM_TCC_PERFMON_SAMPLE_DELAY, 0x00000011}};

/*
 * TCP
 */
static const CounterRegInfo TcpCounterRegAddr[] = {
    {mmTCP_PERFCOUNTER0_SELECT, 0, mmTCP_PERFCOUNTER0_LO, mmTCP_PERFCOUNTER0_HI},
    {mmTCP_PERFCOUNTER1_SELECT, 0, mmTCP_PERFCOUNTER1_LO, mmTCP_PERFCOUNTER1_HI},
    {mmTCP_PERFCOUNTER2_SELECT, 0, mmTCP_PERFCOUNTER2_LO, mmTCP_PERFCOUNTER2_HI},
    {mmTCP_PERFCOUNTER3_SELECT, 0, mmTCP_PERFCOUNTER3_LO, mmTCP_PERFCOUNTER3_HI}};

static const BlockDelayInfo TcpBlockDelayInfo[] = {
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000030},  // se0
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002c},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000028},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000026},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000024},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000020},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001c},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000018},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000016},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000014},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000012},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002c},  // se1
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000028},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000026},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000024},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000020},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001c},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000018},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000016},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000014},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000012},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000010},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000000e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002c},  // se2
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000028},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000026},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000024},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000020},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001c},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000018},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000016},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000014},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000012},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000010},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000000e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000002c},  // se3
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000028},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000026},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000024},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000022},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000020},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001c},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000001a},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000018},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000016},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000014},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000012},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x00000010},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000000e},
    { mmRLC_SPM_TCP_PERFMON_SAMPLE_DELAY, 0x0000000c}};

/*
 * CB
 */
static const CounterRegInfo CbCounterRegAddr[] = {
    {mmCB_PERFCOUNTER0_SELECT, 0, mmCB_PERFCOUNTER0_LO, mmCB_PERFCOUNTER0_HI},
    {mmCB_PERFCOUNTER1_SELECT, 0, mmCB_PERFCOUNTER1_LO, mmCB_PERFCOUNTER1_HI},
    {mmCB_PERFCOUNTER2_SELECT, 0, mmCB_PERFCOUNTER2_LO, mmCB_PERFCOUNTER2_HI},
    {mmCB_PERFCOUNTER3_SELECT, 0, mmCB_PERFCOUNTER3_LO, mmCB_PERFCOUNTER3_HI}};

static const BlockDelayInfo CbBlockDelayInfo[] = {
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x0000001d },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000008 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000014 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000004 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000010 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000005 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x0000000e },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000015 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000000 },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x0000000c },
    { mmRLC_SPM_CB_PERFMON_SAMPLE_DELAY, 0x00000009 }};

/*
 * DB
 */
static const CounterRegInfo DbCounterRegAddr[] = {
    {mmDB_PERFCOUNTER0_SELECT, 0, mmDB_PERFCOUNTER0_LO, mmDB_PERFCOUNTER0_HI},
    {mmDB_PERFCOUNTER1_SELECT, 0, mmDB_PERFCOUNTER1_LO, mmDB_PERFCOUNTER1_HI},
    {mmDB_PERFCOUNTER2_SELECT, 0, mmDB_PERFCOUNTER2_LO, mmDB_PERFCOUNTER2_HI},
    {mmDB_PERFCOUNTER3_SELECT, 0, mmDB_PERFCOUNTER3_LO, mmDB_PERFCOUNTER3_HI}};

static const BlockDelayInfo DbBlockDelayInfo[] = {
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x0000001b },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x0000000c },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000010 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000008 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x0000000c },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000009 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000014 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000008 },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x0000000f },
    { mmRLC_SPM_DB_PERFMON_SAMPLE_DELAY, 0x00000008 }};

/*
 * RLC
 */
static const CounterRegInfo RlcCounterRegAddr[] = {
    {mmRLC_PERFCOUNTER0_SELECT, 0, mmRLC_PERFCOUNTER0_LO, mmRLC_PERFCOUNTER0_HI},
    {mmRLC_PERFCOUNTER1_SELECT, 0, mmRLC_PERFCOUNTER1_LO, mmRLC_PERFCOUNTER1_HI}};

/*
 * SX
 */
static const CounterRegInfo SxCounterRegAddr[] = {
    {mmSX_PERFCOUNTER0_SELECT, 0, mmSX_PERFCOUNTER0_LO, mmSX_PERFCOUNTER0_HI},
    {mmSX_PERFCOUNTER1_SELECT, 0, mmSX_PERFCOUNTER1_LO, mmSX_PERFCOUNTER1_HI},
    {mmSX_PERFCOUNTER2_SELECT, 0, mmSX_PERFCOUNTER2_LO, mmSX_PERFCOUNTER2_HI},
    {mmSX_PERFCOUNTER3_SELECT, 0, mmSX_PERFCOUNTER3_LO, mmSX_PERFCOUNTER3_HI}};

static const BlockDelayInfo SxBlockDelayInfo[] = {
    { mmRLC_SPM_SX_PERFMON_SAMPLE_DELAY, 0x00000006 },
    { mmRLC_SPM_SX_PERFMON_SAMPLE_DELAY, 0x00000006 },
    { mmRLC_SPM_SX_PERFMON_SAMPLE_DELAY, 0x00000008 },
    { mmRLC_SPM_SX_PERFMON_SAMPLE_DELAY, 0x00000004 }};

/*
 * TA
 */
static const CounterRegInfo TaCounterRegAddr[] = {
    {mmTA_PERFCOUNTER0_SELECT, 0, mmTA_PERFCOUNTER0_LO, mmTA_PERFCOUNTER0_HI},
    {mmTA_PERFCOUNTER1_SELECT, 0, mmTA_PERFCOUNTER1_LO, mmTA_PERFCOUNTER1_HI}};

static const BlockDelayInfo TaBlockDelayInfo[] = {
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000002c },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000002a },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000028 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000026 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000024 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000022 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000020 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001e },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001c },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001a },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000018 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000016 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000014 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000012 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000010 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000e },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000028 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000026 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000025 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000023 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000021 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001f },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001d },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001b },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000015 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000f },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000b },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000028 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000026 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000024 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000022 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000020 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001e },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001c },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001a },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000018 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000016 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000014 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000012 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000010 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000e },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000c },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000a },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000027 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000025 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000023 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000021 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001f },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001d },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000001b },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000015 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000f },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x0000000b },
    { mmRLC_SPM_TA_PERFMON_SAMPLE_DELAY, 0x00000009 }};

/*
 * TD
 */
static const CounterRegInfo TdCounterRegAddr[] = {
    {mmTD_PERFCOUNTER0_SELECT, 0, mmTD_PERFCOUNTER0_LO, mmTD_PERFCOUNTER0_HI},
    {mmTD_PERFCOUNTER1_SELECT, 0, mmTD_PERFCOUNTER1_LO, mmTD_PERFCOUNTER1_HI}};

static const BlockDelayInfo TdBlockDelayInfo[] = {
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000002c },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000002a },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000028 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000026 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000024 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000022 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000020 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001e },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001c },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001a },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000018 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000016 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000014 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000012 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000010 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000e },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000028 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000026 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000025 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000023 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000021 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001f },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001d },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001b },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000015 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000f },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000b },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000028 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000027 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000025 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000023 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000021 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001f },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001d },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001b },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000015 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000f },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000b },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000027 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000025 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000023 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000021 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001f },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001d },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000001b },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000019 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000017 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000015 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000013 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000011 },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000f },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000d },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x0000000b },
    { mmRLC_SPM_TD_PERFMON_SAMPLE_DELAY, 0x00000009 }};

/*
 * GDS
 */
static const CounterRegInfo GdsCounterRegAddr[] = {
    {mmGDS_PERFCOUNTER0_SELECT, 0, mmGDS_PERFCOUNTER0_LO, mmGDS_PERFCOUNTER0_HI},
    {mmGDS_PERFCOUNTER1_SELECT, 0, mmGDS_PERFCOUNTER1_LO, mmGDS_PERFCOUNTER1_HI},
    {mmGDS_PERFCOUNTER2_SELECT, 0, mmGDS_PERFCOUNTER2_LO, mmGDS_PERFCOUNTER2_HI},
    {mmGDS_PERFCOUNTER3_SELECT, 0, mmGDS_PERFCOUNTER3_LO, mmGDS_PERFCOUNTER3_HI}};

static const BlockDelayInfo GdsBlockDelayInfo[] = {
    { mmRLC_SPM_GDS_PERFMON_SAMPLE_DELAY, 0x0000002d }
};

/*
 * VGT
 */
static const CounterRegInfo VgtCounterRegAddr[] = {
    {mmVGT_PERFCOUNTER0_SELECT, 0, mmVGT_PERFCOUNTER0_LO, mmVGT_PERFCOUNTER0_HI},
    {mmVGT_PERFCOUNTER1_SELECT, 0, mmVGT_PERFCOUNTER1_LO, mmVGT_PERFCOUNTER1_HI},
    {mmVGT_PERFCOUNTER2_SELECT, 0, mmVGT_PERFCOUNTER2_LO, mmVGT_PERFCOUNTER2_HI},
    {mmVGT_PERFCOUNTER3_SELECT, 0, mmVGT_PERFCOUNTER3_LO, mmVGT_PERFCOUNTER3_HI}};

static const BlockDelayInfo VgtBlockDelayInfo[] = {
    { mmRLC_SPM_VGT_PERFMON_SAMPLE_DELAY, 0x00000027 },
    { mmRLC_SPM_VGT_PERFMON_SAMPLE_DELAY, 0x00000027 },
    { mmRLC_SPM_VGT_PERFMON_SAMPLE_DELAY, 0x00000023 },
    { mmRLC_SPM_VGT_PERFMON_SAMPLE_DELAY, 0x00000024 }};

/*
 * IA
 */
static const CounterRegInfo IaCounterRegAddr[] = {
    {mmIA_PERFCOUNTER0_SELECT, 0, mmIA_PERFCOUNTER0_LO, mmIA_PERFCOUNTER0_HI},
    {mmIA_PERFCOUNTER1_SELECT, 0, mmIA_PERFCOUNTER1_LO, mmIA_PERFCOUNTER1_HI},
    {mmIA_PERFCOUNTER2_SELECT, 0, mmIA_PERFCOUNTER2_LO, mmIA_PERFCOUNTER2_HI},
    {mmIA_PERFCOUNTER3_SELECT, 0, mmIA_PERFCOUNTER3_LO, mmIA_PERFCOUNTER3_HI}};

static const BlockDelayInfo IaBlockDelayInfo[] = {
    { mmRLC_SPM_IA_PERFMON_SAMPLE_DELAY, 0x00000032 }};

/*
 * WD
 */
static const CounterRegInfo WdCounterRegAddr[] = {
    {mmWD_PERFCOUNTER0_SELECT, 0, mmWD_PERFCOUNTER0_LO, mmWD_PERFCOUNTER0_HI},
    {mmWD_PERFCOUNTER1_SELECT, 0, mmWD_PERFCOUNTER1_LO, mmWD_PERFCOUNTER1_HI},
    {mmWD_PERFCOUNTER2_SELECT, 0, mmWD_PERFCOUNTER2_LO, mmWD_PERFCOUNTER2_HI},
    {mmWD_PERFCOUNTER3_SELECT, 0, mmWD_PERFCOUNTER3_LO, mmWD_PERFCOUNTER3_HI}};

/*
 * CPC
 */
static const CounterRegInfo CpcCounterRegAddr[] = {
    {mmCPC_PERFCOUNTER0_SELECT, 0, mmCPC_PERFCOUNTER0_LO, mmCPC_PERFCOUNTER0_HI},
    {mmCPC_PERFCOUNTER1_SELECT, 0, mmCPC_PERFCOUNTER1_LO, mmCPC_PERFCOUNTER1_HI}};

static const BlockDelayInfo CpcBlockDelayInfo[] = {
    { mmRLC_SPM_CPC_PERFMON_SAMPLE_DELAY, 0x0000002c}
};

/*
 * CPF
 */
static const CounterRegInfo CpfCounterRegAddr[] = {
    {mmCPF_PERFCOUNTER0_SELECT, 0, mmCPF_PERFCOUNTER0_LO, mmCPF_PERFCOUNTER0_HI},
    {mmCPF_PERFCOUNTER1_SELECT, 0, mmCPF_PERFCOUNTER1_LO, mmCPF_PERFCOUNTER1_HI}};

static const BlockDelayInfo CpfBlockDelayInfo[] = {
    { mmRLC_SPM_CPF_PERFMON_SAMPLE_DELAY, 0x00000032 }
};

/*
 * CPG
 */
static const CounterRegInfo CpgCounterRegAddr[] = {
    {mmCPG_PERFCOUNTER0_SELECT, 0, mmCPG_PERFCOUNTER0_LO, mmCPG_PERFCOUNTER0_HI},
    {mmCPG_PERFCOUNTER1_SELECT, 0, mmCPG_PERFCOUNTER1_LO, mmCPG_PERFCOUNTER1_HI}};

static const BlockDelayInfo CpgBlockDelayInfo[] = {
    { mmRLC_SPM_CPG_PERFMON_SAMPLE_DELAY, 0x00000030 }
};

// RMI
static const CounterRegInfo RmiCounterRegAddr[] = {
    {mmRMI_PERFCOUNTER0_SELECT, mmRMI_PERF_COUNTER_CNTL, mmRMI_PERFCOUNTER0_LO, mmRMI_PERFCOUNTER0_HI},
    {mmRMI_PERFCOUNTER1_SELECT, mmRMI_PERF_COUNTER_CNTL, mmRMI_PERFCOUNTER1_LO, mmRMI_PERFCOUNTER1_HI},
    {mmRMI_PERFCOUNTER2_SELECT, mmRMI_PERF_COUNTER_CNTL, mmRMI_PERFCOUNTER2_LO, mmRMI_PERFCOUNTER2_HI},
    {mmRMI_PERFCOUNTER3_SELECT, mmRMI_PERF_COUNTER_CNTL, mmRMI_PERFCOUNTER3_LO, mmRMI_PERFCOUNTER3_HI}};

// GCEA
static const CounterRegInfo GceaCounterRegAddr[] = {
    {mmGCEA_PERFCOUNTER0_CFG, mmGCEA_PERFCOUNTER_RSLT_CNTL, mmGCEA_PERFCOUNTER_LO, mmGCEA_PERFCOUNTER_HI},
    {mmGCEA_PERFCOUNTER1_CFG, mmGCEA_PERFCOUNTER_RSLT_CNTL, mmGCEA_PERFCOUNTER_LO, mmGCEA_PERFCOUNTER_HI}};

// ATC
static const CounterRegInfo AtcCounterRegAddr[] = {
    {mmATC_PERFCOUNTER0_CFG, mmATC_PERFCOUNTER_RSLT_CNTL, mmATC_PERFCOUNTER_LO, mmATC_PERFCOUNTER_HI},
    {mmATC_PERFCOUNTER1_CFG, mmATC_PERFCOUNTER_RSLT_CNTL, mmATC_PERFCOUNTER_LO, mmATC_PERFCOUNTER_HI},
    {mmATC_PERFCOUNTER2_CFG, mmATC_PERFCOUNTER_RSLT_CNTL, mmATC_PERFCOUNTER_LO, mmATC_PERFCOUNTER_HI},
    {mmATC_PERFCOUNTER3_CFG, mmATC_PERFCOUNTER_RSLT_CNTL, mmATC_PERFCOUNTER_LO, mmATC_PERFCOUNTER_HI}};

// ATC L2
static const CounterRegInfo AtcL2CounterRegAddr[] = {
    {mmATC_L2_PERFCOUNTER0_CFG, mmATC_L2_PERFCOUNTER_RSLT_CNTL, mmATC_L2_PERFCOUNTER_LO, mmATC_L2_PERFCOUNTER_HI},
    {mmATC_L2_PERFCOUNTER1_CFG, mmATC_L2_PERFCOUNTER_RSLT_CNTL, mmATC_L2_PERFCOUNTER_LO, mmATC_L2_PERFCOUNTER_HI}};

// RPB
static const CounterRegInfo RpbCounterRegAddr[] = {
    {mmRPB_PERFCOUNTER0_CFG, mmRPB_PERFCOUNTER_RSLT_CNTL, mmRPB_PERFCOUNTER_LO, mmRPB_PERFCOUNTER_HI},
    {mmRPB_PERFCOUNTER1_CFG, mmRPB_PERFCOUNTER_RSLT_CNTL, mmRPB_PERFCOUNTER_LO, mmRPB_PERFCOUNTER_HI},
    {mmRPB_PERFCOUNTER2_CFG, mmRPB_PERFCOUNTER_RSLT_CNTL, mmRPB_PERFCOUNTER_LO, mmRPB_PERFCOUNTER_HI},
    {mmRPB_PERFCOUNTER3_CFG, mmRPB_PERFCOUNTER_RSLT_CNTL, mmRPB_PERFCOUNTER_LO, mmRPB_PERFCOUNTER_HI}};

// MC VM L2
#ifdef _mi300_OFFSET_HEADER
static const CounterRegInfo McVmL2CounterRegAddr[] = {
    {mmMC_VM_L2_PERFCOUNTER0_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER1_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER2_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER3_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER4_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER5_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER6_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER7_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER8_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER9_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER10_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER11_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER12_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER13_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER14_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER15_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI}};
#else
static const CounterRegInfo McVmL2CounterRegAddr[] = {
    {mmMC_VM_L2_PERFCOUNTER0_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER1_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER2_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER3_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER4_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER5_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER6_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI},
    {mmMC_VM_L2_PERFCOUNTER7_CFG, mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL, mmMC_VM_L2_PERFCOUNTER_LO, mmMC_VM_L2_PERFCOUNTER_HI}};
#endif

// SDMA
static const CounterRegInfo SdmaCounterRegAddr[] = {
#if defined(_mi300_SDMA_OFFSET_HEADER)
    {mmSDMA_PERFCNT_PERFCOUNTER0_CFG, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA_PERFCNT_PERFCOUNTER_LO, mmSDMA_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA_PERFCNT_PERFCOUNTER1_CFG, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA_PERFCNT_PERFCOUNTER_LO, mmSDMA_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA_PERFCNT_PERFCOUNTER0_CFG_alt_1, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL_alt_1, mmSDMA_PERFCNT_PERFCOUNTER_LO_alt_1, mmSDMA_PERFCNT_PERFCOUNTER_HI_alt_1},
    {mmSDMA_PERFCNT_PERFCOUNTER1_CFG_alt_1, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL_alt_1, mmSDMA_PERFCNT_PERFCOUNTER_LO_alt_1, mmSDMA_PERFCNT_PERFCOUNTER_HI_alt_1},
    {mmSDMA_PERFCNT_PERFCOUNTER0_CFG_alt_2, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL_alt_2, mmSDMA_PERFCNT_PERFCOUNTER_LO_alt_2, mmSDMA_PERFCNT_PERFCOUNTER_HI_alt_2},
    {mmSDMA_PERFCNT_PERFCOUNTER1_CFG_alt_2, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL_alt_2, mmSDMA_PERFCNT_PERFCOUNTER_LO_alt_2, mmSDMA_PERFCNT_PERFCOUNTER_HI_alt_2},
    {mmSDMA_PERFCNT_PERFCOUNTER0_CFG_alt_3, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL_alt_3, mmSDMA_PERFCNT_PERFCOUNTER_LO_alt_3, mmSDMA_PERFCNT_PERFCOUNTER_HI_alt_3},
    {mmSDMA_PERFCNT_PERFCOUNTER1_CFG_alt_3, mmSDMA_PERFCNT_PERFCOUNTER_RSLT_CNTL_alt_3, mmSDMA_PERFCNT_PERFCOUNTER_LO_alt_3, mmSDMA_PERFCNT_PERFCOUNTER_HI_alt_3},
#elif defined(_mi200_SDMA_OFFSET_HEADER)
    {mmSDMA0_PERFCNT_PERFCOUNTER0_CFG, mmSDMA0_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA0_PERFCNT_PERFCOUNTER_LO, mmSDMA0_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA0_PERFCNT_PERFCOUNTER1_CFG, mmSDMA0_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA0_PERFCNT_PERFCOUNTER_LO, mmSDMA0_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA1_PERFCNT_PERFCOUNTER0_CFG, mmSDMA1_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA1_PERFCNT_PERFCOUNTER_LO, mmSDMA1_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA1_PERFCNT_PERFCOUNTER1_CFG, mmSDMA1_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA1_PERFCNT_PERFCOUNTER_LO, mmSDMA1_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA2_PERFCNT_PERFCOUNTER0_CFG, mmSDMA2_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA2_PERFCNT_PERFCOUNTER_LO, mmSDMA2_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA2_PERFCNT_PERFCOUNTER1_CFG, mmSDMA2_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA2_PERFCNT_PERFCOUNTER_LO, mmSDMA2_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA3_PERFCNT_PERFCOUNTER0_CFG, mmSDMA3_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA3_PERFCNT_PERFCOUNTER_LO, mmSDMA3_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA3_PERFCNT_PERFCOUNTER1_CFG, mmSDMA3_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA3_PERFCNT_PERFCOUNTER_LO, mmSDMA3_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA4_PERFCNT_PERFCOUNTER0_CFG, mmSDMA4_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA4_PERFCNT_PERFCOUNTER_LO, mmSDMA4_PERFCNT_PERFCOUNTER_HI},
    {mmSDMA4_PERFCNT_PERFCOUNTER1_CFG, mmSDMA4_PERFCNT_PERFCOUNTER_RSLT_CNTL, mmSDMA4_PERFCNT_PERFCOUNTER_LO, mmSDMA4_PERFCNT_PERFCOUNTER_HI},
#elif defined(_mi100_SDMA_OFFSET_HEADER)
    {mmSDMA0_PERFMON_CNTL, 0, mmSDMA0_PERFCOUNTER0_RESULT, 0},
    {mmSDMA0_PERFMON_CNTL, 0, mmSDMA0_PERFCOUNTER1_RESULT, 0},
    {mmSDMA1_PERFMON_CNTL, 0, mmSDMA1_PERFCOUNTER0_RESULT, 0},
    {mmSDMA1_PERFMON_CNTL, 0, mmSDMA1_PERFCOUNTER1_RESULT, 0},
    {mmSDMA2_PERFMON_CNTL, 0, mmSDMA2_PERFCOUNTER0_RESULT, 0},
    {mmSDMA2_PERFMON_CNTL, 0, mmSDMA2_PERFCOUNTER1_RESULT, 0},
    {mmSDMA3_PERFMON_CNTL, 0, mmSDMA3_PERFCOUNTER0_RESULT, 0},
    {mmSDMA3_PERFMON_CNTL, 0, mmSDMA3_PERFCOUNTER1_RESULT, 0},
    {mmSDMA4_PERFMON_CNTL, 0, mmSDMA4_PERFCOUNTER0_RESULT, 0},
    {mmSDMA4_PERFMON_CNTL, 0, mmSDMA4_PERFCOUNTER1_RESULT, 0},
    {mmSDMA5_PERFMON_CNTL, 0, mmSDMA5_PERFCOUNTER0_RESULT, 0},
    {mmSDMA5_PERFMON_CNTL, 0, mmSDMA5_PERFCOUNTER1_RESULT, 0},
    {mmSDMA6_PERFMON_CNTL, 0, mmSDMA6_PERFCOUNTER0_RESULT, 0},
    {mmSDMA6_PERFMON_CNTL, 0, mmSDMA6_PERFCOUNTER1_RESULT, 0},
    {mmSDMA7_PERFMON_CNTL, 0, mmSDMA7_PERFCOUNTER0_RESULT, 0},
    {mmSDMA7_PERFMON_CNTL, 0, mmSDMA7_PERFCOUNTER1_RESULT, 0}
#else
    {mmSDMA0_PERFMON_CNTL, 0, mmSDMA0_PERFCOUNTER0_RESULT, 0},
    {mmSDMA0_PERFMON_CNTL, 0, mmSDMA0_PERFCOUNTER1_RESULT, 0},
    {mmSDMA1_PERFMON_CNTL, 0, mmSDMA1_PERFCOUNTER0_RESULT, 0},
    {mmSDMA1_PERFMON_CNTL, 0, mmSDMA1_PERFCOUNTER1_RESULT, 0},
#endif
};

// UMC
static const CounterRegInfo UmcCounterRegAddr[] = {
    {mmUMCCH0_PerfMonCtl1,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr1_Lo,    mmUMCCH0_PerfMonCtr1_Hi},
    {mmUMCCH0_PerfMonCtl2,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr2_Lo,    mmUMCCH0_PerfMonCtr2_Hi},
    {mmUMCCH0_PerfMonCtl3,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr3_Lo,    mmUMCCH0_PerfMonCtr3_Hi},
    {mmUMCCH0_PerfMonCtl4,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr4_Lo,    mmUMCCH0_PerfMonCtr4_Hi},
    {mmUMCCH0_PerfMonCtl5,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr5_Lo,    mmUMCCH0_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH0_PerfMonCtl6,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr6_Lo,    mmUMCCH0_PerfMonCtr6_Hi},
    {mmUMCCH0_PerfMonCtl7,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr7_Lo,    mmUMCCH0_PerfMonCtr7_Hi},
    {mmUMCCH0_PerfMonCtl8,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr8_Lo,    mmUMCCH0_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH0_PerfMonCtl9,    mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr9_Lo,    mmUMCCH0_PerfMonCtr9_Hi},
    {mmUMCCH0_PerfMonCtl10,   mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtr10_Lo,   mmUMCCH0_PerfMonCtr10_Hi},
#endif
    {mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtlClk,  mmUMCCH0_PerfMonCtrClk_Lo,  mmUMCCH0_PerfMonCtrClk_Hi},
    {mmUMCCH1_PerfMonCtl1,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr1_Lo,    mmUMCCH1_PerfMonCtr1_Hi},
    {mmUMCCH1_PerfMonCtl2,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr2_Lo,    mmUMCCH1_PerfMonCtr2_Hi},
    {mmUMCCH1_PerfMonCtl3,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr3_Lo,    mmUMCCH1_PerfMonCtr3_Hi},
    {mmUMCCH1_PerfMonCtl4,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr4_Lo,    mmUMCCH1_PerfMonCtr4_Hi},
    {mmUMCCH1_PerfMonCtl5,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr5_Lo,    mmUMCCH1_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH1_PerfMonCtl6,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr6_Lo,    mmUMCCH1_PerfMonCtr6_Hi},
    {mmUMCCH1_PerfMonCtl7,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr7_Lo,    mmUMCCH1_PerfMonCtr7_Hi},
    {mmUMCCH1_PerfMonCtl8,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr8_Lo,    mmUMCCH1_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH1_PerfMonCtl9,    mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr9_Lo,    mmUMCCH1_PerfMonCtr9_Hi},
    {mmUMCCH1_PerfMonCtl10,   mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtr10_Lo,   mmUMCCH1_PerfMonCtr10_Hi},
#endif
    {mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtlClk,  mmUMCCH1_PerfMonCtrClk_Lo,  mmUMCCH1_PerfMonCtrClk_Hi},
    {mmUMCCH2_PerfMonCtl1,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr1_Lo,    mmUMCCH2_PerfMonCtr1_Hi},
    {mmUMCCH2_PerfMonCtl2,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr2_Lo,    mmUMCCH2_PerfMonCtr2_Hi},
    {mmUMCCH2_PerfMonCtl3,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr3_Lo,    mmUMCCH2_PerfMonCtr3_Hi},
    {mmUMCCH2_PerfMonCtl4,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr4_Lo,    mmUMCCH2_PerfMonCtr4_Hi},
    {mmUMCCH2_PerfMonCtl5,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr5_Lo,    mmUMCCH2_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH2_PerfMonCtl6,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr6_Lo,    mmUMCCH2_PerfMonCtr6_Hi},
    {mmUMCCH2_PerfMonCtl7,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr7_Lo,    mmUMCCH2_PerfMonCtr7_Hi},
    {mmUMCCH2_PerfMonCtl8,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr8_Lo,    mmUMCCH2_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH2_PerfMonCtl9,    mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr9_Lo,    mmUMCCH2_PerfMonCtr9_Hi},
    {mmUMCCH2_PerfMonCtl10,   mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtr10_Lo,   mmUMCCH2_PerfMonCtr10_Hi},
#endif
    {mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtlClk,  mmUMCCH2_PerfMonCtrClk_Lo,  mmUMCCH2_PerfMonCtrClk_Hi},
    {mmUMCCH3_PerfMonCtl1,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr1_Lo,    mmUMCCH3_PerfMonCtr1_Hi},
    {mmUMCCH3_PerfMonCtl2,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr2_Lo,    mmUMCCH3_PerfMonCtr2_Hi},
    {mmUMCCH3_PerfMonCtl3,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr3_Lo,    mmUMCCH3_PerfMonCtr3_Hi},
    {mmUMCCH3_PerfMonCtl4,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr4_Lo,    mmUMCCH3_PerfMonCtr4_Hi},
    {mmUMCCH3_PerfMonCtl5,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr5_Lo,    mmUMCCH3_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH3_PerfMonCtl6,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr6_Lo,    mmUMCCH3_PerfMonCtr6_Hi},
    {mmUMCCH3_PerfMonCtl7,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr7_Lo,    mmUMCCH3_PerfMonCtr7_Hi},
    {mmUMCCH3_PerfMonCtl8,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr8_Lo,    mmUMCCH3_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH3_PerfMonCtl9,    mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr9_Lo,    mmUMCCH3_PerfMonCtr9_Hi},
    {mmUMCCH3_PerfMonCtl10,   mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtr10_Lo,   mmUMCCH3_PerfMonCtr10_Hi},
#endif
    {mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtlClk,  mmUMCCH3_PerfMonCtrClk_Lo,  mmUMCCH3_PerfMonCtrClk_Hi},
    {mmUMCCH4_PerfMonCtl1,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr1_Lo,    mmUMCCH4_PerfMonCtr1_Hi},
    {mmUMCCH4_PerfMonCtl2,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr2_Lo,    mmUMCCH4_PerfMonCtr2_Hi},
    {mmUMCCH4_PerfMonCtl3,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr3_Lo,    mmUMCCH4_PerfMonCtr3_Hi},
    {mmUMCCH4_PerfMonCtl4,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr4_Lo,    mmUMCCH4_PerfMonCtr4_Hi},
    {mmUMCCH4_PerfMonCtl5,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr5_Lo,    mmUMCCH4_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH4_PerfMonCtl6,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr6_Lo,    mmUMCCH4_PerfMonCtr6_Hi},
    {mmUMCCH4_PerfMonCtl7,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr7_Lo,    mmUMCCH4_PerfMonCtr7_Hi},
    {mmUMCCH4_PerfMonCtl8,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr8_Lo,    mmUMCCH4_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH4_PerfMonCtl9,    mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr9_Lo,    mmUMCCH4_PerfMonCtr9_Hi},
    {mmUMCCH4_PerfMonCtl10,   mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtr10_Lo,   mmUMCCH4_PerfMonCtr10_Hi},
#endif
    {mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtlClk,  mmUMCCH4_PerfMonCtrClk_Lo,  mmUMCCH4_PerfMonCtrClk_Hi},
    {mmUMCCH5_PerfMonCtl1,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr1_Lo,    mmUMCCH5_PerfMonCtr1_Hi},
    {mmUMCCH5_PerfMonCtl2,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr2_Lo,    mmUMCCH5_PerfMonCtr2_Hi},
    {mmUMCCH5_PerfMonCtl3,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr3_Lo,    mmUMCCH5_PerfMonCtr3_Hi},
    {mmUMCCH5_PerfMonCtl4,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr4_Lo,    mmUMCCH5_PerfMonCtr4_Hi},
    {mmUMCCH5_PerfMonCtl5,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr5_Lo,    mmUMCCH5_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH5_PerfMonCtl6,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr6_Lo,    mmUMCCH5_PerfMonCtr6_Hi},
    {mmUMCCH5_PerfMonCtl7,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr7_Lo,    mmUMCCH5_PerfMonCtr7_Hi},
    {mmUMCCH5_PerfMonCtl8,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr8_Lo,    mmUMCCH5_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH5_PerfMonCtl9,    mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr9_Lo,    mmUMCCH5_PerfMonCtr9_Hi},
    {mmUMCCH5_PerfMonCtl10,   mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtr10_Lo,   mmUMCCH5_PerfMonCtr10_Hi},
#endif
    {mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtlClk,  mmUMCCH5_PerfMonCtrClk_Lo,  mmUMCCH5_PerfMonCtrClk_Hi},
    {mmUMCCH6_PerfMonCtl1,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr1_Lo,    mmUMCCH6_PerfMonCtr1_Hi},
    {mmUMCCH6_PerfMonCtl2,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr2_Lo,    mmUMCCH6_PerfMonCtr2_Hi},
    {mmUMCCH6_PerfMonCtl3,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr3_Lo,    mmUMCCH6_PerfMonCtr3_Hi},
    {mmUMCCH6_PerfMonCtl4,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr4_Lo,    mmUMCCH6_PerfMonCtr4_Hi},
    {mmUMCCH6_PerfMonCtl5,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr5_Lo,    mmUMCCH6_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH6_PerfMonCtl6,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr6_Lo,    mmUMCCH6_PerfMonCtr6_Hi},
    {mmUMCCH6_PerfMonCtl7,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr7_Lo,    mmUMCCH6_PerfMonCtr7_Hi},
    {mmUMCCH6_PerfMonCtl8,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr8_Lo,    mmUMCCH6_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH6_PerfMonCtl9,    mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr9_Lo,    mmUMCCH6_PerfMonCtr9_Hi},
    {mmUMCCH6_PerfMonCtl10,   mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtr10_Lo,   mmUMCCH6_PerfMonCtr10_Hi},
#endif
    {mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtlClk,  mmUMCCH6_PerfMonCtrClk_Lo,  mmUMCCH6_PerfMonCtrClk_Hi},
    {mmUMCCH7_PerfMonCtl1,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr1_Lo,    mmUMCCH7_PerfMonCtr1_Hi},
    {mmUMCCH7_PerfMonCtl2,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr2_Lo,    mmUMCCH7_PerfMonCtr2_Hi},
    {mmUMCCH7_PerfMonCtl3,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr3_Lo,    mmUMCCH7_PerfMonCtr3_Hi},
    {mmUMCCH7_PerfMonCtl4,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr4_Lo,    mmUMCCH7_PerfMonCtr4_Hi},
    {mmUMCCH7_PerfMonCtl5,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr5_Lo,    mmUMCCH7_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH7_PerfMonCtl6,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr6_Lo,    mmUMCCH7_PerfMonCtr6_Hi},
    {mmUMCCH7_PerfMonCtl7,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr7_Lo,    mmUMCCH7_PerfMonCtr7_Hi},
    {mmUMCCH7_PerfMonCtl8,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr8_Lo,    mmUMCCH7_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH7_PerfMonCtl9,    mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr9_Lo,    mmUMCCH7_PerfMonCtr9_Hi},
    {mmUMCCH7_PerfMonCtl10,   mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtr10_Lo,   mmUMCCH7_PerfMonCtr10_Hi},
#endif
    {mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtlClk,  mmUMCCH7_PerfMonCtrClk_Lo,  mmUMCCH7_PerfMonCtrClk_Hi},
    {mmUMCCH8_PerfMonCtl1,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr1_Lo,    mmUMCCH8_PerfMonCtr1_Hi},
    {mmUMCCH8_PerfMonCtl2,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr2_Lo,    mmUMCCH8_PerfMonCtr2_Hi},
    {mmUMCCH8_PerfMonCtl3,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr3_Lo,    mmUMCCH8_PerfMonCtr3_Hi},
    {mmUMCCH8_PerfMonCtl4,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr4_Lo,    mmUMCCH8_PerfMonCtr4_Hi},
    {mmUMCCH8_PerfMonCtl5,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr5_Lo,    mmUMCCH8_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH8_PerfMonCtl6,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr6_Lo,    mmUMCCH8_PerfMonCtr6_Hi},
    {mmUMCCH8_PerfMonCtl7,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr7_Lo,    mmUMCCH8_PerfMonCtr7_Hi},
    {mmUMCCH8_PerfMonCtl8,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr8_Lo,    mmUMCCH8_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH8_PerfMonCtl9,    mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr9_Lo,    mmUMCCH8_PerfMonCtr9_Hi},
    {mmUMCCH8_PerfMonCtl10,   mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtr10_Lo,   mmUMCCH8_PerfMonCtr10_Hi},
#endif
    {mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtlClk,  mmUMCCH8_PerfMonCtrClk_Lo,  mmUMCCH8_PerfMonCtrClk_Hi},
    {mmUMCCH9_PerfMonCtl1,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr1_Lo,    mmUMCCH9_PerfMonCtr1_Hi},
    {mmUMCCH9_PerfMonCtl2,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr2_Lo,    mmUMCCH9_PerfMonCtr2_Hi},
    {mmUMCCH9_PerfMonCtl3,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr3_Lo,    mmUMCCH9_PerfMonCtr3_Hi},
    {mmUMCCH9_PerfMonCtl4,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr4_Lo,    mmUMCCH9_PerfMonCtr4_Hi},
    {mmUMCCH9_PerfMonCtl5,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr5_Lo,    mmUMCCH9_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH9_PerfMonCtl6,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr6_Lo,    mmUMCCH9_PerfMonCtr6_Hi},
    {mmUMCCH9_PerfMonCtl7,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr7_Lo,    mmUMCCH9_PerfMonCtr7_Hi},
    {mmUMCCH9_PerfMonCtl8,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr8_Lo,    mmUMCCH9_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH9_PerfMonCtl9,    mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr9_Lo,    mmUMCCH9_PerfMonCtr9_Hi},
    {mmUMCCH9_PerfMonCtl10,   mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtr10_Lo,   mmUMCCH9_PerfMonCtr10_Hi},
#endif
    {mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtlClk,  mmUMCCH9_PerfMonCtrClk_Lo,  mmUMCCH9_PerfMonCtrClk_Hi},
    {mmUMCCH10_PerfMonCtl1,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr1_Lo,   mmUMCCH10_PerfMonCtr1_Hi},
    {mmUMCCH10_PerfMonCtl2,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr2_Lo,   mmUMCCH10_PerfMonCtr2_Hi},
    {mmUMCCH10_PerfMonCtl3,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr3_Lo,   mmUMCCH10_PerfMonCtr3_Hi},
    {mmUMCCH10_PerfMonCtl4,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr4_Lo,   mmUMCCH10_PerfMonCtr4_Hi},
    {mmUMCCH10_PerfMonCtl5,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr5_Lo,   mmUMCCH10_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH10_PerfMonCtl6,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr6_Lo,   mmUMCCH10_PerfMonCtr6_Hi},
    {mmUMCCH10_PerfMonCtl7,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr7_Lo,   mmUMCCH10_PerfMonCtr7_Hi},
    {mmUMCCH10_PerfMonCtl8,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr8_Lo,   mmUMCCH10_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH10_PerfMonCtl9,   mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr9_Lo,   mmUMCCH10_PerfMonCtr9_Hi},
    {mmUMCCH10_PerfMonCtl10,  mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtr10_Lo,  mmUMCCH10_PerfMonCtr10_Hi},
#endif
    {mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtlClk, mmUMCCH10_PerfMonCtrClk_Lo, mmUMCCH10_PerfMonCtrClk_Hi},
    {mmUMCCH11_PerfMonCtl1,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr1_Lo,   mmUMCCH11_PerfMonCtr1_Hi},
    {mmUMCCH11_PerfMonCtl2,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr2_Lo,   mmUMCCH11_PerfMonCtr2_Hi},
    {mmUMCCH11_PerfMonCtl3,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr3_Lo,   mmUMCCH11_PerfMonCtr3_Hi},
    {mmUMCCH11_PerfMonCtl4,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr4_Lo,   mmUMCCH11_PerfMonCtr4_Hi},
    {mmUMCCH11_PerfMonCtl5,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr5_Lo,   mmUMCCH11_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH11_PerfMonCtl6,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr6_Lo,   mmUMCCH11_PerfMonCtr6_Hi},
    {mmUMCCH11_PerfMonCtl7,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr7_Lo,   mmUMCCH11_PerfMonCtr7_Hi},
    {mmUMCCH11_PerfMonCtl8,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr8_Lo,   mmUMCCH11_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH11_PerfMonCtl9,   mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr9_Lo,   mmUMCCH11_PerfMonCtr9_Hi},
    {mmUMCCH11_PerfMonCtl10,  mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtr10_Lo,  mmUMCCH11_PerfMonCtr10_Hi},
#endif
    {mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtlClk, mmUMCCH11_PerfMonCtrClk_Lo, mmUMCCH11_PerfMonCtrClk_Hi},
    {mmUMCCH12_PerfMonCtl1,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr1_Lo,   mmUMCCH12_PerfMonCtr1_Hi},
    {mmUMCCH12_PerfMonCtl2,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr2_Lo,   mmUMCCH12_PerfMonCtr2_Hi},
    {mmUMCCH12_PerfMonCtl3,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr3_Lo,   mmUMCCH12_PerfMonCtr3_Hi},
    {mmUMCCH12_PerfMonCtl4,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr4_Lo,   mmUMCCH12_PerfMonCtr4_Hi},
    {mmUMCCH12_PerfMonCtl5,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr5_Lo,   mmUMCCH12_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH12_PerfMonCtl6,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr6_Lo,   mmUMCCH12_PerfMonCtr6_Hi},
    {mmUMCCH12_PerfMonCtl7,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr7_Lo,   mmUMCCH12_PerfMonCtr7_Hi},
    {mmUMCCH12_PerfMonCtl8,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr8_Lo,   mmUMCCH12_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH12_PerfMonCtl9,   mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr9_Lo,   mmUMCCH12_PerfMonCtr9_Hi},
    {mmUMCCH12_PerfMonCtl10,  mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtr10_Lo,  mmUMCCH12_PerfMonCtr10_Hi},
#endif
    {mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtlClk, mmUMCCH12_PerfMonCtrClk_Lo, mmUMCCH12_PerfMonCtrClk_Hi},
    {mmUMCCH13_PerfMonCtl1,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr1_Lo,   mmUMCCH13_PerfMonCtr1_Hi},
    {mmUMCCH13_PerfMonCtl2,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr2_Lo,   mmUMCCH13_PerfMonCtr2_Hi},
    {mmUMCCH13_PerfMonCtl3,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr3_Lo,   mmUMCCH13_PerfMonCtr3_Hi},
    {mmUMCCH13_PerfMonCtl4,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr4_Lo,   mmUMCCH13_PerfMonCtr4_Hi},
    {mmUMCCH13_PerfMonCtl5,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr5_Lo,   mmUMCCH13_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH13_PerfMonCtl6,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr6_Lo,   mmUMCCH13_PerfMonCtr6_Hi},
    {mmUMCCH13_PerfMonCtl7,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr7_Lo,   mmUMCCH13_PerfMonCtr7_Hi},
    {mmUMCCH13_PerfMonCtl8,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr8_Lo,   mmUMCCH13_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH13_PerfMonCtl9,   mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr9_Lo,   mmUMCCH13_PerfMonCtr9_Hi},
    {mmUMCCH13_PerfMonCtl10,  mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtr10_Lo,  mmUMCCH13_PerfMonCtr10_Hi},
#endif
    {mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtlClk, mmUMCCH13_PerfMonCtrClk_Lo, mmUMCCH13_PerfMonCtrClk_Hi},
    {mmUMCCH14_PerfMonCtl1,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr1_Lo,   mmUMCCH14_PerfMonCtr1_Hi},
    {mmUMCCH14_PerfMonCtl2,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr2_Lo,   mmUMCCH14_PerfMonCtr2_Hi},
    {mmUMCCH14_PerfMonCtl3,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr3_Lo,   mmUMCCH14_PerfMonCtr3_Hi},
    {mmUMCCH14_PerfMonCtl4,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr4_Lo,   mmUMCCH14_PerfMonCtr4_Hi},
    {mmUMCCH14_PerfMonCtl5,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr5_Lo,   mmUMCCH14_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH14_PerfMonCtl6,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr6_Lo,   mmUMCCH14_PerfMonCtr6_Hi},
    {mmUMCCH14_PerfMonCtl7,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr7_Lo,   mmUMCCH14_PerfMonCtr7_Hi},
    {mmUMCCH14_PerfMonCtl8,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr8_Lo,   mmUMCCH14_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH14_PerfMonCtl9,   mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr9_Lo,   mmUMCCH14_PerfMonCtr9_Hi},
    {mmUMCCH14_PerfMonCtl10,  mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtr10_Lo,  mmUMCCH14_PerfMonCtr10_Hi},
#endif
    {mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtlClk, mmUMCCH14_PerfMonCtrClk_Lo, mmUMCCH14_PerfMonCtrClk_Hi},
    {mmUMCCH15_PerfMonCtl1,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr1_Lo,   mmUMCCH15_PerfMonCtr1_Hi},
    {mmUMCCH15_PerfMonCtl2,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr2_Lo,   mmUMCCH15_PerfMonCtr2_Hi},
    {mmUMCCH15_PerfMonCtl3,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr3_Lo,   mmUMCCH15_PerfMonCtr3_Hi},
    {mmUMCCH15_PerfMonCtl4,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr4_Lo,   mmUMCCH15_PerfMonCtr4_Hi},
    {mmUMCCH15_PerfMonCtl5,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr5_Lo,   mmUMCCH15_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH15_PerfMonCtl6,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr6_Lo,   mmUMCCH15_PerfMonCtr6_Hi},
    {mmUMCCH15_PerfMonCtl7,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr7_Lo,   mmUMCCH15_PerfMonCtr7_Hi},
    {mmUMCCH15_PerfMonCtl8,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr8_Lo,   mmUMCCH15_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH15_PerfMonCtl9,   mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr9_Lo,   mmUMCCH15_PerfMonCtr9_Hi},
    {mmUMCCH15_PerfMonCtl10,  mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtr10_Lo,  mmUMCCH15_PerfMonCtr10_Hi},
#endif
    {mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtlClk, mmUMCCH15_PerfMonCtrClk_Lo, mmUMCCH15_PerfMonCtrClk_Hi},
    {mmUMCCH16_PerfMonCtl1,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr1_Lo,   mmUMCCH16_PerfMonCtr1_Hi},
    {mmUMCCH16_PerfMonCtl2,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr2_Lo,   mmUMCCH16_PerfMonCtr2_Hi},
    {mmUMCCH16_PerfMonCtl3,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr3_Lo,   mmUMCCH16_PerfMonCtr3_Hi},
    {mmUMCCH16_PerfMonCtl4,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr4_Lo,   mmUMCCH16_PerfMonCtr4_Hi},
    {mmUMCCH16_PerfMonCtl5,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr5_Lo,   mmUMCCH16_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH16_PerfMonCtl6,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr6_Lo,   mmUMCCH16_PerfMonCtr6_Hi},
    {mmUMCCH16_PerfMonCtl7,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr7_Lo,   mmUMCCH16_PerfMonCtr7_Hi},
    {mmUMCCH16_PerfMonCtl8,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr8_Lo,   mmUMCCH16_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH16_PerfMonCtl9,   mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr9_Lo,   mmUMCCH16_PerfMonCtr9_Hi},
    {mmUMCCH16_PerfMonCtl10,  mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtr10_Lo,  mmUMCCH16_PerfMonCtr10_Hi},
#endif
    {mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtlClk, mmUMCCH16_PerfMonCtrClk_Lo, mmUMCCH16_PerfMonCtrClk_Hi},
    {mmUMCCH17_PerfMonCtl1,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr1_Lo,   mmUMCCH17_PerfMonCtr1_Hi},
    {mmUMCCH17_PerfMonCtl2,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr2_Lo,   mmUMCCH17_PerfMonCtr2_Hi},
    {mmUMCCH17_PerfMonCtl3,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr3_Lo,   mmUMCCH17_PerfMonCtr3_Hi},
    {mmUMCCH17_PerfMonCtl4,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr4_Lo,   mmUMCCH17_PerfMonCtr4_Hi},
    {mmUMCCH17_PerfMonCtl5,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr5_Lo,   mmUMCCH17_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH17_PerfMonCtl6,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr6_Lo,   mmUMCCH17_PerfMonCtr6_Hi},
    {mmUMCCH17_PerfMonCtl7,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr7_Lo,   mmUMCCH17_PerfMonCtr7_Hi},
    {mmUMCCH17_PerfMonCtl8,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr8_Lo,   mmUMCCH17_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH17_PerfMonCtl9,   mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr9_Lo,   mmUMCCH17_PerfMonCtr9_Hi},
    {mmUMCCH17_PerfMonCtl10,  mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtr10_Lo,  mmUMCCH17_PerfMonCtr10_Hi},
#endif
    {mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtlClk, mmUMCCH17_PerfMonCtrClk_Lo, mmUMCCH17_PerfMonCtrClk_Hi},
    {mmUMCCH18_PerfMonCtl1,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr1_Lo,   mmUMCCH18_PerfMonCtr1_Hi},
    {mmUMCCH18_PerfMonCtl2,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr2_Lo,   mmUMCCH18_PerfMonCtr2_Hi},
    {mmUMCCH18_PerfMonCtl3,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr3_Lo,   mmUMCCH18_PerfMonCtr3_Hi},
    {mmUMCCH18_PerfMonCtl4,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr4_Lo,   mmUMCCH18_PerfMonCtr4_Hi},
    {mmUMCCH18_PerfMonCtl5,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr5_Lo,   mmUMCCH18_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH18_PerfMonCtl6,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr6_Lo,   mmUMCCH18_PerfMonCtr6_Hi},
    {mmUMCCH18_PerfMonCtl7,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr7_Lo,   mmUMCCH18_PerfMonCtr7_Hi},
    {mmUMCCH18_PerfMonCtl8,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr8_Lo,   mmUMCCH18_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH18_PerfMonCtl9,   mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr9_Lo,   mmUMCCH18_PerfMonCtr9_Hi},
    {mmUMCCH18_PerfMonCtl10,  mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtr10_Lo,  mmUMCCH18_PerfMonCtr10_Hi},
#endif
    {mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtlClk, mmUMCCH18_PerfMonCtrClk_Lo, mmUMCCH18_PerfMonCtrClk_Hi},
    {mmUMCCH19_PerfMonCtl1,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr1_Lo,   mmUMCCH19_PerfMonCtr1_Hi},
    {mmUMCCH19_PerfMonCtl2,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr2_Lo,   mmUMCCH19_PerfMonCtr2_Hi},
    {mmUMCCH19_PerfMonCtl3,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr3_Lo,   mmUMCCH19_PerfMonCtr3_Hi},
    {mmUMCCH19_PerfMonCtl4,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr4_Lo,   mmUMCCH19_PerfMonCtr4_Hi},
    {mmUMCCH19_PerfMonCtl5,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr5_Lo,   mmUMCCH19_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH19_PerfMonCtl6,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr6_Lo,   mmUMCCH19_PerfMonCtr6_Hi},
    {mmUMCCH19_PerfMonCtl7,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr7_Lo,   mmUMCCH19_PerfMonCtr7_Hi},
    {mmUMCCH19_PerfMonCtl8,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr8_Lo,   mmUMCCH19_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH19_PerfMonCtl9,   mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr9_Lo,   mmUMCCH19_PerfMonCtr9_Hi},
    {mmUMCCH19_PerfMonCtl10,  mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtr10_Lo,  mmUMCCH19_PerfMonCtr10_Hi},
#endif
    {mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtlClk, mmUMCCH19_PerfMonCtrClk_Lo, mmUMCCH19_PerfMonCtrClk_Hi},
    {mmUMCCH20_PerfMonCtl1,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr1_Lo,   mmUMCCH20_PerfMonCtr1_Hi},
    {mmUMCCH20_PerfMonCtl2,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr2_Lo,   mmUMCCH20_PerfMonCtr2_Hi},
    {mmUMCCH20_PerfMonCtl3,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr3_Lo,   mmUMCCH20_PerfMonCtr3_Hi},
    {mmUMCCH20_PerfMonCtl4,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr4_Lo,   mmUMCCH20_PerfMonCtr4_Hi},
    {mmUMCCH20_PerfMonCtl5,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr5_Lo,   mmUMCCH20_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH20_PerfMonCtl6,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr6_Lo,   mmUMCCH20_PerfMonCtr6_Hi},
    {mmUMCCH20_PerfMonCtl7,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr7_Lo,   mmUMCCH20_PerfMonCtr7_Hi},
    {mmUMCCH20_PerfMonCtl8,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr8_Lo,   mmUMCCH20_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH20_PerfMonCtl9,   mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr9_Lo,   mmUMCCH20_PerfMonCtr9_Hi},
    {mmUMCCH20_PerfMonCtl10,  mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtr10_Lo,  mmUMCCH20_PerfMonCtr10_Hi},
#endif
    {mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtlClk, mmUMCCH20_PerfMonCtrClk_Lo, mmUMCCH20_PerfMonCtrClk_Hi},
    {mmUMCCH21_PerfMonCtl1,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr1_Lo,   mmUMCCH21_PerfMonCtr1_Hi},
    {mmUMCCH21_PerfMonCtl2,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr2_Lo,   mmUMCCH21_PerfMonCtr2_Hi},
    {mmUMCCH21_PerfMonCtl3,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr3_Lo,   mmUMCCH21_PerfMonCtr3_Hi},
    {mmUMCCH21_PerfMonCtl4,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr4_Lo,   mmUMCCH21_PerfMonCtr4_Hi},
    {mmUMCCH21_PerfMonCtl5,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr5_Lo,   mmUMCCH21_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH21_PerfMonCtl6,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr6_Lo,   mmUMCCH21_PerfMonCtr6_Hi},
    {mmUMCCH21_PerfMonCtl7,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr7_Lo,   mmUMCCH21_PerfMonCtr7_Hi},
    {mmUMCCH21_PerfMonCtl8,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr8_Lo,   mmUMCCH21_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH21_PerfMonCtl9,   mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr9_Lo,   mmUMCCH21_PerfMonCtr9_Hi},
    {mmUMCCH21_PerfMonCtl10,  mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtr10_Lo,  mmUMCCH21_PerfMonCtr10_Hi},
#endif
    {mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtlClk, mmUMCCH21_PerfMonCtrClk_Lo, mmUMCCH21_PerfMonCtrClk_Hi},
    {mmUMCCH22_PerfMonCtl1,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr1_Lo,   mmUMCCH22_PerfMonCtr1_Hi},
    {mmUMCCH22_PerfMonCtl2,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr2_Lo,   mmUMCCH22_PerfMonCtr2_Hi},
    {mmUMCCH22_PerfMonCtl3,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr3_Lo,   mmUMCCH22_PerfMonCtr3_Hi},
    {mmUMCCH22_PerfMonCtl4,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr4_Lo,   mmUMCCH22_PerfMonCtr4_Hi},
    {mmUMCCH22_PerfMonCtl5,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr5_Lo,   mmUMCCH22_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH22_PerfMonCtl6,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr6_Lo,   mmUMCCH22_PerfMonCtr6_Hi},
    {mmUMCCH22_PerfMonCtl7,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr7_Lo,   mmUMCCH22_PerfMonCtr7_Hi},
    {mmUMCCH22_PerfMonCtl8,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr8_Lo,   mmUMCCH22_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH22_PerfMonCtl9,   mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr9_Lo,   mmUMCCH22_PerfMonCtr9_Hi},
    {mmUMCCH22_PerfMonCtl10,  mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtr10_Lo,  mmUMCCH22_PerfMonCtr10_Hi},
#endif
    {mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtlClk, mmUMCCH22_PerfMonCtrClk_Lo, mmUMCCH22_PerfMonCtrClk_Hi},
    {mmUMCCH23_PerfMonCtl1,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr1_Lo,   mmUMCCH23_PerfMonCtr1_Hi},
    {mmUMCCH23_PerfMonCtl2,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr2_Lo,   mmUMCCH23_PerfMonCtr2_Hi},
    {mmUMCCH23_PerfMonCtl3,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr3_Lo,   mmUMCCH23_PerfMonCtr3_Hi},
    {mmUMCCH23_PerfMonCtl4,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr4_Lo,   mmUMCCH23_PerfMonCtr4_Hi},
    {mmUMCCH23_PerfMonCtl5,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr5_Lo,   mmUMCCH23_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH23_PerfMonCtl6,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr6_Lo,   mmUMCCH23_PerfMonCtr6_Hi},
    {mmUMCCH23_PerfMonCtl7,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr7_Lo,   mmUMCCH23_PerfMonCtr7_Hi},
    {mmUMCCH23_PerfMonCtl8,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr8_Lo,   mmUMCCH23_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH23_PerfMonCtl9,   mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr9_Lo,   mmUMCCH23_PerfMonCtr9_Hi},
    {mmUMCCH23_PerfMonCtl10,  mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtr10_Lo,  mmUMCCH23_PerfMonCtr10_Hi},
#endif
    {mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtlClk, mmUMCCH23_PerfMonCtrClk_Lo, mmUMCCH23_PerfMonCtrClk_Hi},
    {mmUMCCH24_PerfMonCtl1,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr1_Lo,   mmUMCCH24_PerfMonCtr1_Hi},
    {mmUMCCH24_PerfMonCtl2,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr2_Lo,   mmUMCCH24_PerfMonCtr2_Hi},
    {mmUMCCH24_PerfMonCtl3,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr3_Lo,   mmUMCCH24_PerfMonCtr3_Hi},
    {mmUMCCH24_PerfMonCtl4,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr4_Lo,   mmUMCCH24_PerfMonCtr4_Hi},
    {mmUMCCH24_PerfMonCtl5,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr5_Lo,   mmUMCCH24_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH24_PerfMonCtl6,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr6_Lo,   mmUMCCH24_PerfMonCtr6_Hi},
    {mmUMCCH24_PerfMonCtl7,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr7_Lo,   mmUMCCH24_PerfMonCtr7_Hi},
    {mmUMCCH24_PerfMonCtl8,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr8_Lo,   mmUMCCH24_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH24_PerfMonCtl9,   mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr9_Lo,   mmUMCCH24_PerfMonCtr9_Hi},
    {mmUMCCH24_PerfMonCtl10,  mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtr10_Lo,  mmUMCCH24_PerfMonCtr10_Hi},
#endif
    {mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtlClk, mmUMCCH24_PerfMonCtrClk_Lo, mmUMCCH24_PerfMonCtrClk_Hi},
    {mmUMCCH25_PerfMonCtl1,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr1_Lo,   mmUMCCH25_PerfMonCtr1_Hi},
    {mmUMCCH25_PerfMonCtl2,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr2_Lo,   mmUMCCH25_PerfMonCtr2_Hi},
    {mmUMCCH25_PerfMonCtl3,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr3_Lo,   mmUMCCH25_PerfMonCtr3_Hi},
    {mmUMCCH25_PerfMonCtl4,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr4_Lo,   mmUMCCH25_PerfMonCtr4_Hi},
    {mmUMCCH25_PerfMonCtl5,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr5_Lo,   mmUMCCH25_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH25_PerfMonCtl6,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr6_Lo,   mmUMCCH25_PerfMonCtr6_Hi},
    {mmUMCCH25_PerfMonCtl7,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr7_Lo,   mmUMCCH25_PerfMonCtr7_Hi},
    {mmUMCCH25_PerfMonCtl8,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr8_Lo,   mmUMCCH25_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH25_PerfMonCtl9,   mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr9_Lo,   mmUMCCH25_PerfMonCtr9_Hi},
    {mmUMCCH25_PerfMonCtl10,  mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtr10_Lo,  mmUMCCH25_PerfMonCtr10_Hi},
#endif
    {mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtlClk, mmUMCCH25_PerfMonCtrClk_Lo, mmUMCCH25_PerfMonCtrClk_Hi},
    {mmUMCCH26_PerfMonCtl1,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr1_Lo,   mmUMCCH26_PerfMonCtr1_Hi},
    {mmUMCCH26_PerfMonCtl2,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr2_Lo,   mmUMCCH26_PerfMonCtr2_Hi},
    {mmUMCCH26_PerfMonCtl3,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr3_Lo,   mmUMCCH26_PerfMonCtr3_Hi},
    {mmUMCCH26_PerfMonCtl4,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr4_Lo,   mmUMCCH26_PerfMonCtr4_Hi},
    {mmUMCCH26_PerfMonCtl5,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr5_Lo,   mmUMCCH26_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH26_PerfMonCtl6,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr6_Lo,   mmUMCCH26_PerfMonCtr6_Hi},
    {mmUMCCH26_PerfMonCtl7,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr7_Lo,   mmUMCCH26_PerfMonCtr7_Hi},
    {mmUMCCH26_PerfMonCtl8,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr8_Lo,   mmUMCCH26_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH26_PerfMonCtl9,   mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr9_Lo,   mmUMCCH26_PerfMonCtr9_Hi},
    {mmUMCCH26_PerfMonCtl10,  mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtr10_Lo,  mmUMCCH26_PerfMonCtr10_Hi},
#endif
    {mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtlClk, mmUMCCH26_PerfMonCtrClk_Lo, mmUMCCH26_PerfMonCtrClk_Hi},
    {mmUMCCH27_PerfMonCtl1,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr1_Lo,   mmUMCCH27_PerfMonCtr1_Hi},
    {mmUMCCH27_PerfMonCtl2,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr2_Lo,   mmUMCCH27_PerfMonCtr2_Hi},
    {mmUMCCH27_PerfMonCtl3,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr3_Lo,   mmUMCCH27_PerfMonCtr3_Hi},
    {mmUMCCH27_PerfMonCtl4,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr4_Lo,   mmUMCCH27_PerfMonCtr4_Hi},
    {mmUMCCH27_PerfMonCtl5,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr5_Lo,   mmUMCCH27_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH27_PerfMonCtl6,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr6_Lo,   mmUMCCH27_PerfMonCtr6_Hi},
    {mmUMCCH27_PerfMonCtl7,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr7_Lo,   mmUMCCH27_PerfMonCtr7_Hi},
    {mmUMCCH27_PerfMonCtl8,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr8_Lo,   mmUMCCH27_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH27_PerfMonCtl9,   mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr9_Lo,   mmUMCCH27_PerfMonCtr9_Hi},
    {mmUMCCH27_PerfMonCtl10,  mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtr10_Lo,  mmUMCCH27_PerfMonCtr10_Hi},
#endif
    {mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtlClk, mmUMCCH27_PerfMonCtrClk_Lo, mmUMCCH27_PerfMonCtrClk_Hi},
    {mmUMCCH28_PerfMonCtl1,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr1_Lo,   mmUMCCH28_PerfMonCtr1_Hi},
    {mmUMCCH28_PerfMonCtl2,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr2_Lo,   mmUMCCH28_PerfMonCtr2_Hi},
    {mmUMCCH28_PerfMonCtl3,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr3_Lo,   mmUMCCH28_PerfMonCtr3_Hi},
    {mmUMCCH28_PerfMonCtl4,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr4_Lo,   mmUMCCH28_PerfMonCtr4_Hi},
    {mmUMCCH28_PerfMonCtl5,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr5_Lo,   mmUMCCH28_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH28_PerfMonCtl6,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr6_Lo,   mmUMCCH28_PerfMonCtr6_Hi},
    {mmUMCCH28_PerfMonCtl7,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr7_Lo,   mmUMCCH28_PerfMonCtr7_Hi},
    {mmUMCCH28_PerfMonCtl8,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr8_Lo,   mmUMCCH28_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH28_PerfMonCtl9,   mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr9_Lo,   mmUMCCH28_PerfMonCtr9_Hi},
    {mmUMCCH28_PerfMonCtl10,  mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtr10_Lo,  mmUMCCH28_PerfMonCtr10_Hi},
#endif
    {mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtlClk, mmUMCCH28_PerfMonCtrClk_Lo, mmUMCCH28_PerfMonCtrClk_Hi},
    {mmUMCCH29_PerfMonCtl1,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr1_Lo,   mmUMCCH29_PerfMonCtr1_Hi},
    {mmUMCCH29_PerfMonCtl2,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr2_Lo,   mmUMCCH29_PerfMonCtr2_Hi},
    {mmUMCCH29_PerfMonCtl3,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr3_Lo,   mmUMCCH29_PerfMonCtr3_Hi},
    {mmUMCCH29_PerfMonCtl4,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr4_Lo,   mmUMCCH29_PerfMonCtr4_Hi},
    {mmUMCCH29_PerfMonCtl5,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr5_Lo,   mmUMCCH29_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH29_PerfMonCtl6,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr6_Lo,   mmUMCCH29_PerfMonCtr6_Hi},
    {mmUMCCH29_PerfMonCtl7,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr7_Lo,   mmUMCCH29_PerfMonCtr7_Hi},
    {mmUMCCH29_PerfMonCtl8,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr8_Lo,   mmUMCCH29_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH29_PerfMonCtl9,   mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr9_Lo,   mmUMCCH29_PerfMonCtr9_Hi},
    {mmUMCCH29_PerfMonCtl10,  mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtr10_Lo,  mmUMCCH29_PerfMonCtr10_Hi},
#endif
    {mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtlClk, mmUMCCH29_PerfMonCtrClk_Lo, mmUMCCH29_PerfMonCtrClk_Hi},
    {mmUMCCH30_PerfMonCtl1,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr1_Lo,    mmUMCCH30_PerfMonCtr1_Hi},
    {mmUMCCH30_PerfMonCtl2,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr2_Lo,    mmUMCCH30_PerfMonCtr2_Hi},
    {mmUMCCH30_PerfMonCtl3,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr3_Lo,    mmUMCCH30_PerfMonCtr3_Hi},
    {mmUMCCH30_PerfMonCtl4,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr4_Lo,    mmUMCCH30_PerfMonCtr4_Hi},
    {mmUMCCH30_PerfMonCtl5,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr5_Lo,    mmUMCCH30_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH30_PerfMonCtl6,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr6_Lo,    mmUMCCH30_PerfMonCtr6_Hi},
    {mmUMCCH30_PerfMonCtl7,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr7_Lo,    mmUMCCH30_PerfMonCtr7_Hi},
    {mmUMCCH30_PerfMonCtl8,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr8_Lo,    mmUMCCH30_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH30_PerfMonCtl9,   mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr9_Lo,   mmUMCCH30_PerfMonCtr9_Hi},
    {mmUMCCH30_PerfMonCtl10,  mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtr10_Lo,  mmUMCCH30_PerfMonCtr10_Hi},
#endif
    {mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtlClk, mmUMCCH30_PerfMonCtrClk_Lo,  mmUMCCH30_PerfMonCtrClk_Hi},
    {mmUMCCH31_PerfMonCtl1,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr1_Lo,    mmUMCCH31_PerfMonCtr1_Hi},
    {mmUMCCH31_PerfMonCtl2,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr2_Lo,    mmUMCCH31_PerfMonCtr2_Hi},
    {mmUMCCH31_PerfMonCtl3,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr3_Lo,    mmUMCCH31_PerfMonCtr3_Hi},
    {mmUMCCH31_PerfMonCtl4,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr4_Lo,    mmUMCCH31_PerfMonCtr4_Hi},
    {mmUMCCH31_PerfMonCtl5,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr5_Lo,    mmUMCCH31_PerfMonCtr5_Hi},
#if defined(_mi200_OFFSET_HEADER) || defined(_mi300_OFFSET_HEADER)
    {mmUMCCH31_PerfMonCtl6,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr6_Lo,    mmUMCCH31_PerfMonCtr6_Hi},
    {mmUMCCH31_PerfMonCtl7,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr7_Lo,    mmUMCCH31_PerfMonCtr7_Hi},
    {mmUMCCH31_PerfMonCtl8,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr8_Lo,    mmUMCCH31_PerfMonCtr8_Hi},
#endif
#ifdef _mi300_OFFSET_HEADER
    {mmUMCCH31_PerfMonCtl9,   mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr9_Lo,   mmUMCCH31_PerfMonCtr9_Hi},
    {mmUMCCH31_PerfMonCtl10,  mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtr10_Lo,  mmUMCCH31_PerfMonCtr10_Hi},
#endif
    {mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtlClk, mmUMCCH31_PerfMonCtrClk_Lo,  mmUMCCH31_PerfMonCtrClk_Hi}};

// Counter block info table
// SPM global blocks: CPG, CPC, CPF, GDS, TCC, TCA, IA, TCS
// SPM shader engine blocks: CB, DB, SC, SX, TA, TD, TCP, VGT, SQG, SPI, PA
// Counter block CB
static const GpuBlockInfo CbCounterBlockInfo = {"CB", CbCounterBlockId, CbCounterBlockNumInstances, CbCounterBlockMaxEvent, CbCounterBlockNumCounters, CbCounterRegAddr, gfx9_cntx_prim::select_value<regCB_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockCleanAttr, CbBlockDelayInfo, SPM_SE_BLOCK_NAME_CB};
// Counter block DB
static const GpuBlockInfo DbCounterBlockInfo = {"DB", DbCounterBlockId, DbCounterBlockNumInstances, DbCounterBlockMaxEvent, DbCounterBlockNumCounters, DbCounterRegAddr, gfx9_cntx_prim::select_value<regDB_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockCleanAttr, DbBlockDelayInfo, SPM_SE_BLOCK_NAME_DB};
// Counter block GRBM
static const GpuBlockInfo GrbmCounterBlockInfo = {"GRBM", GrbmCounterBlockId, 1, GrbmCounterBlockMaxEvent, GrbmCounterBlockNumCounters, GrbmCounterRegAddr, gfx9_cntx_prim::select_value<regGRBM_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr|CounterBlockGRBMAttr};
// Counter block GRBMSE
static const GpuBlockInfo GrbmSeCounterBlockInfo = {"GRBM_SE", GrbmSeCounterBlockId, 1, GrbmSeCounterBlockMaxEvent, GrbmSeCounterBlockNumCounters, GrbmSeCounterRegAddr, gfx9_cntx_prim::select_value<regGRBM_SE0_PERFCOUNTER_SELECT>, CounterBlockDfltAttr};
// Counter block PA_SU
static const GpuBlockInfo PaSuCounterBlockInfo = {"PA_SU", PaSuCounterBlockId, 1, PaSuCounterBlockMaxEvent, PaSuCounterBlockNumCounters, PaSuCounterRegAddr, gfx9_cntx_prim::select_value<regPA_SU_PERFCOUNTER0_SELECT>, CounterBlockSeAttr, PaSuBlockDelayInfo, SPM_SE_BLOCK_NAME_PA};
// Counter block PA_SC
static const GpuBlockInfo PaScCounterBlockInfo = {"PA_SC", PaScCounterBlockId, 1, PaScCounterBlockMaxEvent, PaScCounterBlockNumCounters, PaScCounterRegAddr, gfx9_cntx_prim::select_value<regPA_SC_PERFCOUNTER0_SELECT>, CounterBlockSeAttr, PaScBlockDelayInfo, SPM_SE_BLOCK_NAME_SC};
// Counter block SPI
static const GpuBlockInfo SpiCounterBlockInfo = {"SPI", SpiCounterBlockId, 1, SpiCounterBlockMaxEvent, SpiCounterBlockNumCounters, SpiCounterRegAddr, gfx9_cntx_prim::select_value<regSPI_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockSPIAttr, SpiBlockDelayInfo, SPM_SE_BLOCK_NAME_SPI};
// Counter block SQ
static const GpuBlockInfo SqCounterBlockInfo = {"SQ", SqCounterBlockId, 1, SqCounterBlockMaxEvent, SqCounterBlockNumCounters, SqCounterRegAddr, gfx9_cntx_prim::sq_select_value, CounterBlockSeAttr|CounterBlockSqAttr, SqBlockDelayInfo, SPM_SE_BLOCK_NAME_SQG};
static const GpuBlockInfo SqGsCounterBlockInfo = {"SQ_GS", SqCounterBlockId, 1, SqCounterBlockMaxEvent, SqCounterBlockNumCounters, SqCounterRegAddr, gfx9_cntx_prim::sq_select_value, CounterBlockSeAttr|CounterBlockSqAttr};
static const GpuBlockInfo SqVsCounterBlockInfo = {"SQ_VS", SqCounterBlockId, 1, SqCounterBlockMaxEvent, SqCounterBlockNumCounters, SqCounterRegAddr, gfx9_cntx_prim::sq_select_value, CounterBlockSeAttr|CounterBlockSqAttr};
static const GpuBlockInfo SqPsCounterBlockInfo = {"SQ_PS", SqCounterBlockId, 1, SqCounterBlockMaxEvent, SqCounterBlockNumCounters, SqCounterRegAddr, gfx9_cntx_prim::sq_select_value, CounterBlockSeAttr|CounterBlockSqAttr};
static const GpuBlockInfo SqHsCounterBlockInfo = {"SQ_HS", SqCounterBlockId, 1, SqCounterBlockMaxEvent, SqCounterBlockNumCounters, SqCounterRegAddr, gfx9_cntx_prim::sq_select_value, CounterBlockSeAttr|CounterBlockSqAttr};
static const GpuBlockInfo SqCsCounterBlockInfo = {"SQ_CS", SqCounterBlockId, 1, SqCounterBlockMaxEvent, SqCounterBlockNumCounters, SqCounterRegAddr, gfx9_cntx_prim::sq_select_value, CounterBlockSeAttr|CounterBlockSqAttr};
// Counter block SX
static const GpuBlockInfo SxCounterBlockInfo = {"SX", SxCounterBlockId, 1, SxCounterBlockMaxEvent, SxCounterBlockNumCounters, SxCounterRegAddr, gfx9_cntx_prim::select_value<regSX_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockCleanAttr, SxBlockDelayInfo, SPM_SE_BLOCK_NAME_SX};
// Counter block TA
static const GpuBlockInfo TaCounterBlockInfo = {"TA", TaCounterBlockId, TaCounterBlockNumInstances, TaCounterBlockMaxEvent, TaCounterBlockNumCounters, TaCounterRegAddr, gfx9_cntx_prim::select_value<regTA_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockTcAttr, TaBlockDelayInfo, SPM_SE_BLOCK_NAME_TA};
// Counter block TCA
static const GpuBlockInfo TcaCounterBlockInfo = {"TCA", TcaCounterBlockId, TcaCounterBlockNumInstances, TcaCounterBlockMaxEvent, TcaCounterBlockNumCounters, TcaCounterRegAddr, gfx9_cntx_prim::select_value<regTCA_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr|CounterBlockTcAttr|CounterBlockSpmGlobalAttr, TcaBlockDelayInfo, SPM_GLOBAL_BLOCK_NAME_TCA};
// Counter block TCC
static const GpuBlockInfo TccCounterBlockInfo = {"TCC", TccCounterBlockId, TccCounterBlockNumInstances, TccCounterBlockMaxEvent, TccCounterBlockNumCounters, TccCounterRegAddr, gfx9_cntx_prim::select_value<regTCC_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr|CounterBlockTcAttr|CounterBlockSpmGlobalAttr, TccBlockDelayInfo, SPM_GLOBAL_BLOCK_NAME_TCC};
// Counter block TD
static const GpuBlockInfo TdCounterBlockInfo = {"TD", TdCounterBlockId, TdCounterBlockNumInstances, TdCounterBlockMaxEvent, TdCounterBlockNumCounters, TdCounterRegAddr, gfx9_cntx_prim::select_value<regTD_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockTcAttr, TdBlockDelayInfo, SPM_SE_BLOCK_NAME_TD};
// Counter block TCP
static const GpuBlockInfo TcpCounterBlockInfo = {"TCP", TcpCounterBlockId, TcpCounterBlockNumInstances, TcpCounterBlockMaxEvent, TcpCounterBlockNumCounters, TcpCounterRegAddr, gfx9_cntx_prim::select_value<regTCP_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockTcAttr, TcpBlockDelayInfo, SPM_SE_BLOCK_NAME_TCP};
// Counter block GDS
static const GpuBlockInfo GdsCounterBlockInfo = {"GDS", GdsCounterBlockId, 1, GdsCounterBlockMaxEvent, GdsCounterBlockNumCounters, GdsCounterRegAddr, gfx9_cntx_prim::select_value<regGDS_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr|CounterBlockSpmGlobalAttr, GdsBlockDelayInfo, SPM_GLOBAL_BLOCK_NAME_GDS};
// Counter block VGT
 static const GpuBlockInfo VgtCounterBlockInfo = {"VGT", VgtCounterBlockId, 1, VgtCounterBlockMaxEvent, VgtCounterBlockNumCounters, VgtCounterRegAddr, gfx9_cntx_prim::select_value<regVGT_PERFCOUNTER0_SELECT>, CounterBlockSeAttr, VgtBlockDelayInfo, SPM_SE_BLOCK_NAME_VGT};
// Counter block IA
static const GpuBlockInfo IaCounterBlockInfo = {"IA", IaCounterBlockId, 1, IaCounterBlockMaxEvent, IaCounterBlockNumCounters, IaCounterRegAddr, gfx9_cntx_prim::select_value<regIA_PERFCOUNTER0_SELECT>, CounterBlockSeAttr|CounterBlockSpmGlobalAttr, IaBlockDelayInfo, SPM_GLOBAL_BLOCK_NAME_IA};
// Counter block WD
static const GpuBlockInfo WdCounterBlockInfo = {"WD", WdCounterBlockId, 1, WdCounterBlockMaxEvent, WdCounterBlockNumCounters, WdCounterRegAddr, gfx9_cntx_prim::select_value<regWD_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr};
// Counter block CPC
static const GpuBlockInfo CpcCounterBlockInfo = {"CPC", CpcCounterBlockId, 1, CpcCounterBlockMaxEvent, CpcCounterBlockNumCounters, CpcCounterRegAddr, gfx9_cntx_prim::select_value<regCPC_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr|CounterBlockSpmGlobalAttr, CpcBlockDelayInfo, SPM_GLOBAL_BLOCK_NAME_CPC};
// Counter block CPF
static const GpuBlockInfo CpfCounterBlockInfo = {"CPF", CpfCounterBlockId, 1, CpfCounterBlockMaxEvent, CpfCounterBlockNumCounters, CpfCounterRegAddr, gfx9_cntx_prim::select_value<regCPF_PERFCOUNTER0_SELECT>, CounterBlockDfltAttr|CounterBlockSpmGlobalAttr, CpfBlockDelayInfo, SPM_GLOBAL_BLOCK_NAME_CPF/*2*/};
// Counter block MCVM L2
static const GpuBlockInfo McVmL2CounterBlockInfo = {"MCVML2", McVmL2CounterBlockId, 1, McVmL2CounterBlockMaxEvent, McVmL2CounterBlockNumCounters, McVmL2CounterRegAddr, gfx9_cntx_prim::mc_select_value<regMC_VM_L2_PERFCOUNTER0_CFG>, CounterBlockMcAttr};
// Counter block ATC L2
static const GpuBlockInfo AtcL2CounterBlockInfo = {"ATCL2", AtcL2CounterBlockId, 1, AtcL2CounterBlockMaxEvent, AtcL2CounterBlockNumCounters, AtcL2CounterRegAddr, gfx9_cntx_prim::mc_select_value<regATC_L2_PERFCOUNTER0_CFG>, CounterBlockMcAttr};
// Counter block ATC
static const GpuBlockInfo AtcCounterBlockInfo = {"ATC", AtcCounterBlockId, 1, AtcCounterBlockMaxEvent, AtcCounterBlockNumCounters, AtcCounterRegAddr, gfx9_cntx_prim::mc_select_value<regATC_PERFCOUNTER0_CFG>, CounterBlockAtcAttr|CounterBlockAidAttr};
// Counter block GCEA
static const GpuBlockInfo GceaCounterBlockInfo = {"GCEA", GceaCounterBlockId, GceaCounterBlockNumInstances, GceaCounterBlockMaxEvent, GceaCounterBlockNumCounters, GceaCounterRegAddr, gfx9_cntx_prim::mc_select_value<regGCEA_PERFCOUNTER0_CFG>, CounterBlockMcAttr};
// Counter block RPB
static const GpuBlockInfo RpbCounterBlockInfo = {"RPB", RpbCounterBlockId, 1, RpbCounterBlockMaxEvent, RpbCounterBlockNumCounters, RpbCounterRegAddr, gfx9_cntx_prim::mc_select_value<regRPB_PERFCOUNTER0_CFG>, CounterBlockRpbAttr|CounterBlockAidAttr};
// Counter block SDMA
static const GpuBlockInfo SdmaCounterBlockInfo = {"SDMA", SdmaCounterBlockId, SdmaCounterBlockNumInstances, SdmaCounterBlockMaxEvent, SdmaCounterBlockNumCounters, SdmaCounterRegAddr, NULL, CounterBlockSdmaAttr|CounterBlockExplInstAttr|CounterBlockAidAttr};
// Counter block UMC
static const GpuBlockInfo UmcCounterBlockInfo = {"UMC", UmcCounterBlockId, UmcCounterBlockNumInstances, UmcCounterBlockMaxEvent, UmcCounterBlockNumCounters, UmcCounterRegAddr, NULL, CounterBlockUmcAttr|CounterBlockExplInstAttr|CounterBlockAidAttr};
}  // namespace gfx9
}  // namespace gfxip

#endif  //  _GFX9_BLOCKTABLE_H_
